services:
  postgres:
    image: postgres:17
    container_name: whitex-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: whitex
      POSTGRES_PASSWORD: whitex_password
      POSTGRES_DB: whitex

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: